version: '3'

services:
  base: &base
    platform: linux/amd64
    image: chatwoot/chatwoot:latest
    env_file: ./env/.env ## Change this file for customized env variables
    volumes:
      - ./data/storage:/app/storage

  rails:
    <<: *base
    platform: linux/amd64
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: [ 'bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    restart: always

  sidekiq:
    <<: *base
    platform: linux/amd64
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: [ 'bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml' ]
    restart: always

  postgres:
    platform: linux/amd64
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=postgres

  redis:
    platform: linux/amd64
    image: redis:alpine
    restart: always
    command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
    env_file: ./env/.env
    volumes:
      - ./data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
